### ISSUE TITLE
sensor application deployed to cloud foundry but the generated url is not working

### ISSUE THREAD

**Issue by Harikb183** [SAP-samples/teched2020-DEV164#17]
i am successfully developed project(sensor manager app) and also deployed it to cloud foundry , but the application is not loading with the generated url [https://033b4803trial-aws-tb4x0rx0-dev-dappsdashboard-approuter.cfapps.us10.hana.ondemand.com/kcsensormanager/index.html]
![Screenshot (11)](https://user-images.githubusercontent.com/103194837/162206501-e2e6ac42-c0cf-418c-a94a-490e756ee2c4.png)
![Screenshot (9)](https://user-images.githubusercontent.com/103194837/162206827-bab55365-238e-4b80-ae40-37d943796dad.png)
![Screenshot (10)](https://user-images.githubusercontent.com/103194837/162206862-e9c16f53-40dc-4fea-af5d-e195e230673e.png)
![Screenshot (12)](https://user-images.githubusercontent.com/103194837/162207888-c5721970-b898-436c-83fb-0496adf5df28.png)

**Comment by flovogt** [comment]
Hi @Harikb183 ,
thanks for reporting your issue here. First of all, awesome that you've achieved this tutorial so far and I hope you've enjoyed it.
From the screenshots above it's quite hard to guess whats the reason for the non working link. So I can also only guess. Have you changed the `welcomeFile` property of the `xs-app.json` like described in https://github.com/SAP-samples/teched2020-DEV164/tree/main/exercises/ex11#exercise-114---configure-the-app-router-for-redirect?. Ensure that the value is identical with `sap.app/id` in the `manifest.json`. Also please check the BTP logs for further information whats going wrong.

**Comment by flovogt** [comment]
Closed because author didn't respond for a long time.
